### ISSUE TITLE
software dependencies issues in the docker

### ISSUE THREAD

**Issue by galpinf** [haudiobe/5GVideo#1]
Some software are not fixed for reference (e.g. gpac) and may give different results depending on the downloaded version.
where:  docker/Dockerfile

**Comment by haudiobe** [comment]
My proposal is that we agree on a correct version and lock in this version.

**Comment by haudiobe** [comment]
As we do not use FFMPEG or gpac, but HDRTools. In this case we document the supported versions of the software versions. Will be documented in the docker file.

**Comment by nlsdvl** [comment]
JM/HM/VTM & HDRTools versions are now explicitly set in the dockerfile, gpac/libav have been removed.
