### ISSUE TITLE
software dependencies not met

### ISSUE THREAD

**Issue by galpinf** [haudiobe/5GVideo#2]
In order to build gpac using ffavfilter API,gpac configuration to use local ffmpef is needed (though the --use-ffmpeg=/home/deps/ffmpeg-4.3.1 )
where: docker/Dockerfile

**Comment by haudiobe** [comment]
We should reduce the amount of dependencies if possible. In particular if there is a mix of licenses.

**Comment by haudiobe** [comment]
Seems solved with the docker file.
