### ISSUE TITLE
software dependencies not met for ffmpeg

### ISSUE THREAD

**Issue by galpinf** [haudiobe/5GVideo#3]
In order to use avfilter with ffmpeg, avfilter should also be downloaded and built.
where: docker/Dockerfile

**Comment by nlsdvl** [comment]
I'm not sure I understand the issue, libavfilter being part of the ffmpeg code base, it is generated as part of the ffmpeg build

**Comment by galpinf** [comment]
Yes sorry, the issue was coming when I tried to build gpac using ffmpeg system package (which then requires to install separate libavfilter-dev package). Starting from ffmpeg source and selecting the correct configuration should be fine.
