### ISSUE TITLE
software dependencies and control

### ISSUE THREAD

**Issue by galpinf** [haudiobe/5GVideo#4]
Current scripts use gpac -> ffmpeg -> avfilter to compute PSNR and SSIM metrics in a non controlable way. Also these software partly use LGPL licences.
As HDR metrics might require dependency HDRTools which already integrate PSNR and (MS)SSIM in a controlable way, dependencies can be further reduced by using only HDRTools.
Note: PSNR is also configurable to use JVET PSNR formula.

**Comment by haudiobe** [comment]
We should reduce the amount of dependencies if possible. In particular if there is a mix of licenses. We should also have only a single way library to do metrics. HDRTools may be a good way forward.

**Comment by nlsdvl** [comment]
That totally makes sens to me. libav only provides limited metrics, and it is intend to implement HDRtools for HDR metrics.

**Comment by haudiobe** [comment]
As we do not use FFMPEG or gpac, but HDRTools. In this case we document the supported versions of the software versions. Will be documented in the docker file. Needs HDRTools implementation.

**Comment by nlsdvl** [comment]
removed libav/ffmpeg & gpac dependencies.
