### ISSUE TITLE
software issue for partial sequence

### ISSUE THREAD

**Issue by galpinf** [haudiobe/5GVideo#5]
When running the metrics on a chunk of sequence (i.e. not the whole sequence), the number of frames of the sequence is not taken into account in the gpac parameters and final metrics are wrongly computed on the wrong frames (last decoded frame is compared to all following frames in the original sequence).

**Comment by haudiobe** [comment]
OK, there should be a clear means to align the compared frames. This is why I would prefer to use mp4 files to have the same timing. As long as this is not possible, we need to fix this differently.

**Comment by galpinf** [comment]
If we go forward using HDRTools, the issue should be solved (as this is a gpac issue) since there is a way in the parameters to control start/end for each sequences.

**Comment by nlsdvl** [comment]
@galpinf You are right, this has been overlooked and is currently not supported by the script. It should also support skipping frames at the beginning of the sequence as featured in the encoders.

While gpac currently doesn't provide a way to address a segment of the sequence, the libavfilter graph can be modified to specify start/stop frame numbers to take into account until HDRtools is supported.

**Comment by haudiobe** [comment]
With the use of HDRTools this is supported, except when doing VMAF.

For now, we will not report VMAF metrics for chunks, if VMAF is used standalone. If VMAF is included in Libav, this would be supported. Nils implements an option to add libav or not. In the latter case, VMAF will not be reported.

**Comment by nlsdvl** [comment]
a sequence is now configurable as 'reference_segment' on the anchor definition.
