### ISSUE TITLE
PSNR computation

### ISSUE THREAD

**Issue by galpinf** [haudiobe/5GVideo#7]
Infinite PSNR is not handled the correct way by avfilter (inf is reported).

**Comment by haudiobe** [comment]
We need to define a value for this. Please provide a suggestion. I propose that we set the max value to 100 and document this in the Technical Report.

**Comment by galpinf** [comment]
In JVET, the PSNR is capped at 999.0.
In HDRToosl, looking at the code, it seems taht the SSE is capped at 1e-20 (so in practice the maximum PSNR might vary, but always above 200 dB.
static inline double psnr(double maxSampleValue, int samples, double sseDistortion) {
  return (double) (10.0 * log10((double) maxSampleValue * (double) maxSampleValue * (double) ((double) samples / (sseDistortion < 1e-20 ? 1e-20 : sseDistortion))));
}

**Comment by nlsdvl** [comment]
Indeed, the script doesn't currently handle this case, the values could be capped.

> the SSE is capped at 1e-20
this seems to be the case only when HDRtools is compiled with the JM_PSNR option.
https://gitlab.com/standards/HDRTools/-/blob/master/common/inc/IFunctions.H#L416

HDRtools also provides a JVET specific PSNR implementation, disabled by default, which could be used: https://gitlab.com/standards/HDRTools/-/blob/master/cfg/HDRMetrics.cfg#L25
https://gitlab.com/standards/HDRTools/-/blob/master/common/src/DistortionMetric.cpp#L127

**Comment by haudiobe** [comment]
Compile HDRTools with the JVET-specific PSNR option. Nils will implement this. JM-PSNR option will be disabled to not have 1e-20 for SSE. Nils will do.

**Comment by nlsdvl** [comment]
JVET specific PSNR is enabled
