### ISSUE TITLE
PSNR accuracy

### ISSUE THREAD

**Issue by galpinf** [haudiobe/5GVideo#8]
Currently returned values (in ascii) of frame PSNR does not have enough accuracy for per-chunk computation where all individual PSNR are averaged.

**Comment by haudiobe** [comment]
We should make this very accurate, e.g. 10 digits. there is no need to unnecessarily truncate this.

**Comment by galpinf** [comment]
in HDRTools, it seems the default is 3 digits, then for full accuracy, one can activate the hex mode which output the full double in hex.

**Comment by haudiobe** [comment]
We will use HDRTools with hex mode. Will be implemented.

**Comment by nlsdvl** [comment]
added HDRTools w/ support for hex metrics
